function LB = OCP_GEN_LB(in1,in2,in3)
%OCP_GEN_LB
%    LB = OCP_GEN_LB(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Nov-2020 17:34:33

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
u5 = in1(5,:);
u6 = in1(6,:);
u7 = in1(7,:);
u8 = in1(8,:);
x8 = in2(8,:);
x9 = in2(9,:);
x10 = in2(10,:);
x11 = in2(11,:);
x12 = in2(12,:);
x13 = in2(13,:);
x14 = in2(14,:);
t2 = pi./2.0;
LB = u8.*1.5e-3+pi.*7.0e-4-log(t2+u8+x8)-log(t2+u8+x9)-log(t2+u8+x10)-log(t2+u8+x11)-log(t2+u8+x12)-log(t2+u8+x13)-log(t2+u8+x14)-log(u1+1.0e+1)-log(u2+1.0e+1)-log(u3+1.0e+1)-log(u4+1.0e+1)-log(u5+1.0e+1)-log(u6+1.0e+1)-log(u7+1.0e+1)-log(t2+u8-x8)-log(t2+u8-x9)-log(t2+u8-x10)-log(t2+u8-x11)-log(t2+u8-x12)-log(t2+u8-x13)-log(t2+u8-x14)-log(-u1+1.0e+1)-log(-u2+1.0e+1)-log(-u3+1.0e+1)-log(-u4+1.0e+1)-log(-u5+1.0e+1)-log(-u6+1.0e+1)-log(-u7+1.0e+1)-log(u8)+7.0./5.0e+2;
