function C = OCP_GEN_C(in1,in2,in3,parIdx)
%OCP_GEN_C
%    C = OCP_GEN_C(IN1,IN2,IN3,PARIDX)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Nov-2020 17:34:35

C = zeros(0,1);
