function [LB,LBu,LBx] = OCP_GEN_LB_LBu_LBx(in1,in2,in3)
%OCP_GEN_LB_LBU_LBX
%    [LB,LBU,LBX] = OCP_GEN_LB_LBU_LBX(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    06-Nov-2020 17:34:33

u1 = in1(1,:);
u2 = in1(2,:);
u3 = in1(3,:);
u4 = in1(4,:);
u5 = in1(5,:);
u6 = in1(6,:);
u7 = in1(7,:);
u8 = in1(8,:);
x8 = in2(8,:);
x9 = in2(9,:);
x10 = in2(10,:);
x11 = in2(11,:);
x12 = in2(12,:);
x13 = in2(13,:);
x14 = in2(14,:);
t2 = u1+1.0e+1;
t3 = u2+1.0e+1;
t4 = u3+1.0e+1;
t5 = u4+1.0e+1;
t6 = u5+1.0e+1;
t7 = u6+1.0e+1;
t8 = u7+1.0e+1;
t9 = -x8;
t10 = -x9;
t11 = -x10;
t12 = -x11;
t13 = -x12;
t14 = -x13;
t15 = -x14;
t16 = pi./2.0;
t17 = t16+u8+x8;
t18 = t16+u8+x9;
t19 = t16+u8+x10;
t20 = t16+u8+x11;
t21 = t16+u8+x12;
t22 = t16+u8+x13;
t23 = t16+u8+x14;
t24 = t9+t16+u8;
t25 = t10+t16+u8;
t26 = t11+t16+u8;
t27 = t12+t16+u8;
t28 = t13+t16+u8;
t29 = t14+t16+u8;
t30 = t15+t16+u8;
LB = u8.*1.5e-3+pi.*7.0e-4-log(-u1+1.0e+1)-log(-u2+1.0e+1)-log(-u3+1.0e+1)-log(-u4+1.0e+1)-log(-u5+1.0e+1)-log(-u6+1.0e+1)-log(-u7+1.0e+1)-log(t2)-log(t3)-log(t4)-log(t5)-log(t6)-log(t7)-log(t8)-log(t17)-log(t18)-log(t19)-log(t20)-log(t21)-log(t22)-log(t23)-log(t24)-log(t25)-log(t26)-log(t27)-log(t28)-log(t29)-log(t30)-log(u8)+7.0./5.0e+2;
if nargout > 1
    t31 = 1.0./t17;
    t32 = 1.0./t18;
    t33 = 1.0./t19;
    t34 = 1.0./t20;
    t35 = 1.0./t21;
    t36 = 1.0./t22;
    t37 = 1.0./t23;
    t39 = 1.0./t24;
    t41 = 1.0./t25;
    t43 = 1.0./t26;
    t45 = 1.0./t27;
    t47 = 1.0./t28;
    t49 = 1.0./t29;
    t51 = 1.0./t30;
    t38 = -t31;
    t40 = -t32;
    t42 = -t33;
    t44 = -t34;
    t46 = -t35;
    t48 = -t36;
    t50 = -t37;
    LBu = [-1.0./(u1-1.0e+1)-1.0./t2,-1.0./(u2-1.0e+1)-1.0./t3,-1.0./(u3-1.0e+1)-1.0./t4,-1.0./(u4-1.0e+1)-1.0./t5,-1.0./(u5-1.0e+1)-1.0./t6,-1.0./(u6-1.0e+1)-1.0./t7,-1.0./(u7-1.0e+1)-1.0./t8,t38-t39+t40-t41+t42-t43+t44-t45+t46-t47+t48-t49+t50-t51-1.0./u8+1.5e-3];
end
if nargout > 2
    LBx = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,t38+t39,t40+t41,t42+t43,t44+t45,t46+t47,t48+t49,t50+t51];
end
